# Generated by Django 4.2.10 on 2024-03-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_city_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
