# Generated by Django 4.2.10 on 2024-03-14 11:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='users/static/images/profile_default_image.png', max_length=255, verbose_name='image'),
        ),
    ]
