# Generated by Django 4.2.10 on 2024-03-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.CharField(default='General Discussion', max_length=255),
        ),
    ]
