# Generated by Django 4.2.10 on 2024-03-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_status_conversation_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='slug',
        ),
    ]
