# Generated by Django 4.2.10 on 2024-03-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_featured_image'),
        ('messaging', '0004_remove_conversation_topic_alter_conversation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='products.product'),
        ),
    ]
