# Generated by Django 4.2.10 on 2024-03-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_contact',
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
