# Generated by Django 4.2.10 on 2024-03-10 06:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='static/images/product-default-image.jpg', max_length=255, verbose_name='image'),
        ),
    ]
